# see: https://github.com/Chuanwise/network-watchdog

enable: true
debug: false
introduce: false
interval: 6000
threshold: 1
urls:
  - https://www.qq.com
  - https://www.baidu.com
  - https://cn.bing.com