name: NetworkWatchdog
version: 1.0
author: Chuanwise
main: cn.chuanwise.networkwatchdog.NetworkWatchdogPlugin
softdepend:
  - PlaceholderAPI

commands:
  network-watchdog:
    aliases:
      - nw
      - networkwatchdog